name: cerebro_patio_app
description: App para tÃ©cnicos de Cerebro Patio.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & DI
  provider: ^6.1.1
  
  # Networking
  http: ^1.2.0
  dio: ^5.4.0
  
  # Storage/Cache
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # UI/Utils
  intl: ^0.19.0
  google_fonts: ^6.1.0
  signature: ^5.4.0 # For daily signature
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  jwt_decoder: ^2.0.1
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
